### ISSUE TITLE
Beautifying the messages coming from the hooks

### ISSUE THREAD

**Issue by lnxpy** [lnxpy/cookiecutter-pyaction#6]
- using terminal coloring tricks and giving the messages a better look (no need for relying on any 3rd party)

**Comment by Farhaduneci** [comment]
I would like to work on this one @lnxpy, If no one else currently does! What do you think?

**Comment by lnxpy** [comment]
@Farhaduneci that's amazing. Take your time. :))

**Comment by lnxpy** [comment]
@Farhaduneci that's amazing. Take your time. :))

**Comment by Farhaduneci** [comment]
Ok, please share any ideas that might inspire me 🤗
